starting worker pid=12420 on localhost:11717 at 20:43:31.711
starting worker pid=17552 on localhost:11717 at 20:43:31.746
starting worker pid=3176 on localhost:11717 at 20:45:10.823
starting worker pid=15060 on localhost:11717 at 20:45:10.873
starting worker pid=21864 on localhost:11717 at 20:47:28.581
starting worker pid=7520 on localhost:11717 at 20:47:28.632
starting worker pid=17520 on localhost:11717 at 20:58:51.830
starting worker pid=20964 on localhost:11717 at 20:58:51.884
starting worker pid=13408 on localhost:11717 at 20:59:33.895
starting worker pid=20784 on localhost:11717 at 20:59:33.926
starting worker pid=22032 on localhost:11717 at 21:00:44.147
starting worker pid=26224 on localhost:11717 at 21:00:44.162
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: Warning message:
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: Warning messages:
In (function (chem.cas = NULL, chem.name = NULL, dtxsid = NULL,  :
  Funbound.plasma adjusted for in vitro partitioning (Pearce, 2017).
Execution halted
1: In (function (chem.cas = NULL, chem.name = NULL, dtxsid = NULL,  :
  Fraction unbound = 0, changed to 0.005.
2: In (function (chem.cas = NULL, chem.name = NULL, dtxsid = NULL,  :
  Funbound.plasma adjusted for in vitro partitioning (Pearce, 2017).
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: Warning message:
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
In addition: Warning messages:
In (function (chem.cas = NULL, chem.name = NULL, dtxsid = NULL,  :
  Funbound.plasma adjusted for in vitro partitioning (Pearce, 2017).
1: In (function (chem.cas = NULL, chem.name = NULL, dtxsid = NULL,  :
  Fraction unbound = 0, changed to 0.005.
2: Execution halted
In (function (chem.cas = NULL, chem.name = NULL, dtxsid = NULL,  :
  Funbound.plasma adjusted for in vitro partitioning (Pearce, 2017).
Execution halted
starting worker pid=15924 on localhost:11187 at 17:31:08.341
starting worker pid=15688 on localhost:11187 at 17:31:08.378
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... doTryCatch -> recvData -> recvData.SOCKnode -> unserialize
Execution halted
Execution halted
